# .github/workflows/deploy-slash.yml 1228
# [偵錯模式 v1] 捕獲並顯示 Nginx 和 Gunicorn 的詳細日誌，以找出根本原因

name: 'Deploy to VM with Nginx: Slash (Subdirectory)'

on:
  push:
    branches:
      - main
    paths:
      - 'deployment/Slash/**'
      - '.github/workflows/deploy-slash.yml'
  workflow_dispatch:

env:
  # --- 請確認以下變數與您的 GCP 環境相符 ---
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_VM_ZONE: ${{ secrets.GCP_VM_ZONE }}
  GCP_VM_NAME: ${{ secrets.GCP_VM_NAME }}
  GCP_VM_USER: 'tibame20250527' # 直接指定 VM 上的使用者名稱
  
  # --- 部署路徑設定 ---
  # 來源: GitHub Repo 中的子目錄
  LOCAL_APP_PATH: 'deployment/Slash' 
  # 目標: VM 上的絕對路徑
  REMOTE_APP_DIR: '/home/tibame20250527/Slash' 
  
  # --- 服務設定 ---
  NGINX_APP_NAME: 'slash-app'
  GUNICORN_PORT: 5002

jobs:
  deploy-to-vm:
    name: 'Deploy Slash App to VM'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: '1. Checkout Repository Code'
        uses: actions/checkout@v4

      - name: '2. Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: '3. Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: '4. Create Remote Directory and Set Permissions'
        run: |
          gcloud compute ssh ${{ env.GCP_VM_USER }}@${{ env.GCP_VM_NAME }} --zone ${{ env.GCP_VM_ZONE }} --project ${{ env.GCP_PROJECT_ID }} -- << EOF
            mkdir -p ${{ env.REMOTE_APP_DIR }}
            sudo chown -R ${{ env.GCP_VM_USER }}:${{ env.GCP_VM_USER }} ${{ env.REMOTE_APP_DIR }}
          EOF

      - name: '5. Copy Application Files to VM'
        run: |
          gcloud compute scp --recurse ./${{ env.LOCAL_APP_PATH }}/ ${{ env.GCP_VM_USER }}@${{ env.GCP_VM_NAME }}:${{ env.REMOTE_APP_DIR }} --zone ${{ env.GCP_VM_ZONE }} --project ${{ env.GCP_PROJECT_ID }}
      
      - name: '6. Install, Configure, and Restart Services on VM'
        run: |
          gcloud compute ssh ${{ env.GCP_VM_USER }}@${{ env.GCP_VM_NAME }} --zone ${{ env.GCP_VM_ZONE }} --project ${{ env.GCP_PROJECT_ID }} -- << 'EOF'
            set -e

            REMOTE_APP_DIR="${{ env.REMOTE_APP_DIR }}"
            NGINX_APP_NAME="${{ env.NGINX_APP_NAME }}"
            GUNICORN_PORT="${{ env.GUNICORN_PORT }}"
            
            echo "--- 1-4. Installing dependencies and activating venv ---"
            sudo apt-get update
            sudo apt-get install -y nginx python3-pip python3-venv
            cd ${REMOTE_APP_DIR}
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install -r requirements.txt

            echo "--- 5. Creating .env file ---"
            printf '%s\n' \
              "DB_TYPE='${{ secrets.DB_TYPE }}'" \
              "DB_HOST='${{ secrets.DB_HOST }}'" \
              "DB_USER='${{ secrets.DB_USER }}'" \
              "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" \
              "DB_DATABASE='${{ secrets.DB_DATABASE }}'" > .env

            echo "--- 6. Creating Nginx configuration ---"
            printf '%s\n' \
              "server {" \
              "    listen 80;" \
              "    server_name ${{ secrets.GCP_VM_IP }};" \
              "    location / { proxy_pass http://127.0.0.1:${GUNICORN_PORT}; proxy_set_header Host \$host; }" \
              "}" | sudo tee /etc/nginx/sites-available/${NGINX_APP_NAME} > /dev/null

            echo "--- 7. Starting Gunicorn in background ---"
            pkill -f "gunicorn.*--bind 127.0.0.1:${GUNICORN_PORT} app:app" || echo "Gunicorn not running, which is fine."
            nohup gunicorn --workers 3 --bind 127.0.0.1:${GUNICORN_PORT} app:app > ~/gunicorn-slash.log 2>&1 &
            
            echo "--- Waiting 5 seconds for Gunicorn to start up... ---"
            sleep 5

            echo "--- 8. Enabling Nginx site and attempting to restart Nginx ---"
            sudo ln -sf /etc/nginx/sites-available/${NGINX_APP_NAME} /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo nginx -t
            
            # --- 關鍵偵錯：如果 Nginx 重啟失敗，就顯示所有相關日誌 ---
            if ! sudo systemctl restart nginx; then
              echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
              echo "!!! Nginx restart FAILED. Fetching debug logs... !!!"
              echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
              sleep 2 
              echo "--- [DEBUG] Nginx Service Status ---"
              sudo systemctl status nginx.service --no-pager
              echo "--- [DEBUG] Nginx System Journal (Last 50 lines) ---"
              sudo journalctl -xeu nginx.service --no-pager -n 50
              echo "--- [DEBUG] Gunicorn Application Log ---"
              cat ~/gunicorn-slash.log
              echo "--- End of Debug Logs ---"
              exit 1
            fi

            deactivate
            echo "--- Deployment to ${REMOTE_APP_DIR} completed successfully! ---"
          EOF