# .github/workflows/deploy-slash.yml (修正版) 1542
# [修正版] 僅部署應用程式並啟動 Gunicorn，Nginx 設定由外部統一管理

name: 'Deploy to VM: Slash (Bare Metal)'

on:
  push:
    branches:
      - main
    paths:
      - 'deployment/Slash/**'
      - '.github/workflows/deploy-slash.yml'
  workflow_dispatch:

env:
  # --- 請確認以下變數與您的 GCP 環境相符 ---
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_VM_ZONE: ${{ secrets.GCP_VM_ZONE }}
  GCP_VM_NAME: ${{ secrets.GCP_VM_NAME }}
  GCP_VM_USER: 'tibame20250527'
  
  # --- 部署路徑設定 ---
  LOCAL_APP_PATH: 'deployment/Slash' 
  REMOTE_APP_DIR: '/home/tibame20250527/Slash' 
  
  # --- 服務設定 ---
  GUNICORN_PORT: 5002 # Slash App 使用 5002 Port

jobs:
  deploy-to-vm:
    name: 'Deploy Slash App to VM'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: '1. Checkout Repository Code'
        uses: actions/checkout@v4

      - name: '2. Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: '3. Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: '4. Create Remote Directory'
        run: |
          gcloud compute ssh ${{ env.GCP_VM_USER }}@${{ env.GCP_VM_NAME }} --zone ${{ env.GCP_VM_ZONE }} --project ${{ env.GCP_PROJECT_ID }} --command="mkdir -p ${{ env.REMOTE_APP_DIR }}"

      - name: '5. Copy Application Files to VM'
        run: |
          gcloud compute scp --recurse ./${{ env.LOCAL_APP_PATH }}/ ${{ env.GCP_VM_USER }}@${{ env.GCP_VM_NAME }}:${{ env.REMOTE_APP_DIR }} --zone ${{ env.GCP_VM_ZONE }} --project ${{ env.GCP_PROJECT_ID }}
      
      - name: '6. Install Dependencies and Restart Gunicorn on VM'
        run: |
          gcloud compute ssh ${{ env.GCP_VM_USER }}@${{ env.GCP_VM_NAME }} --zone ${{ env.GCP_VM_ZONE }} --project ${{ env.GCP_PROJECT_ID }} -- << 'EOF'
            # 如果任何指令失敗，則立即停止腳本
            set -e

            # 從 GitHub Actions 傳入的環境變數
            REMOTE_APP_DIR="${{ env.REMOTE_APP_DIR }}"
            GUNICORN_PORT="${{ env.GUNICORN_PORT }}"
            
            echo "--- 1. Navigating to application directory: ${REMOTE_APP_DIR} ---"
            cd ${REMOTE_APP_DIR}

            echo "--- 2. Updating system packages and installing Python tools ---"
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-venv

            echo "--- 3. Creating/Activating Python virtual environment ---"
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate

            echo "--- 4. Installing Python dependencies ---"
            pip install --upgrade pip
            pip install -r requirements.txt

            echo "--- 5. Creating .env file with secrets ---"
            cat > .env << EOT
            DB_TYPE='${{ secrets.DB_TYPE }}'
            DB_HOST='${{ secrets.DB_HOST }}'
            DB_USER='${{ secrets.DB_USER }}'
            DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
            DB_DATABASE='${{ secrets.DB_DATABASE }}'
            EOT

            echo "--- 6. Stopping old Gunicorn and starting new one ---"
            # 使用 pkill 精準地停止與此應用相關的 Gunicorn 進程
            pkill -f "gunicorn.*--bind 127.0.0.1:${GUNICORN_PORT} app:app" || echo "Gunicorn not running, which is fine."

            # 使用 Gunicorn 啟動應用，'app:app' 指的是 app.py 檔案中的 app 物件
            # 在背景運行，並將日誌輸出到家目錄的 gunicorn-slash.log
            nohup gunicorn --workers 3 --bind 127.0.0.1:${GUNICORN_PORT} app:app > ~/gunicorn-slash.log 2>&1 &

            deactivate
            echo "--- Deployment to ${REMOTE_APP_DIR} completed successfully! ---"
          EOF